# Numpy 

## 创建数组

In [46]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b[1,2]=10
print('a的shape:{}'.format(a.shape))
print('b的shape:{}'.format(b.shape))
print('a的数据类型:{}'.format(a.dtype))
print('b:{}'.format(b))

a的shape:(3,)
b的shape:(3, 3)
a的数据类型:int64
b:[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]


## 结构数组

In [45]:
import numpy as np
person_type = np.dtype({
    'names':['name', 'age', 'Chinese', 'Math', 'English'],
    'formats':['S32','i', 'i', 'i', 'f']})  # 数据类型
"""
  |name|age|Chinese|Math|English
0 |    |   |       |    |       
1 |    |...
"""
peoples = np.array([("ZhangSan",78,23,19, 80.5),("LiSi",25,88,91,87),
       ("WangWu",66,16,82,98.5)],
    dtype=person_type)
ages = peoples[:]['age']
chineses = peoples[:]['Chinese']
maths = peoples[:]['Math']
englishs = peoples[:]['English']
print('取所有ages的平均:{}'.format(np.mean(ages)))
print('取所有chinese的平均:{}'.format(np.mean(chineses)))
print('取所有math的平均:{}'.format(np.mean(maths)))
print('取所有english的平均:{}'.format(np.mean(englishs)))

取所有ages的平均:56.333333333333336
取所有chinese的平均:42.333333333333336
取所有math的平均:64.0
取所有english的平均:88.66666412353516


## 连续数组

In [44]:
import numpy as np

x1 = np.arange(1,10,2)
x2 = np.linspace(1,10,5)
print('arange:{}'.format(x1))
print('linspace:{}'.format(x2))

arange:[1 3 5 7 9]
linspace:[ 1.    3.25  5.5   7.75 10.  ]


## 算术运算

In [42]:
import numpy as np

x1 = np.arange(1,10,2)
x2 = np.linspace(1,10,5)
# 加运算，各个元素对应相加,同x1+x2
print('加法:{}'.format(np.add(x1,x2)))
print(x1+x2)
# 减运算，各个元素对应相减,同x1-x2
print('减法:{}'.format(np.subtract(x1,x2)))
print(x1-x2)
# 乘运算，各个元素对应相乘，同x1*x2
print('乘法:{}'.format(np.multiply(x1,x2)))
print(x1*x2)
# 除运算，各个元素对应相除，同x1/x2
print('除法:{}'.format(np.divide(x1,x2)))
print(x1/x2)
# 乘方运算，前者元素为底，后者元素为幂，同x1**x2
print('乘方:{}'.format(np.power(x1,x2)))
print(x1**x2)
# 取余运算，各个元素对应取余，同x1%x2
print('模:{}'.format(np.mod(x1,x2)))  # 也可以用np.remainder
print(x1%x2)
# 点乘运算，矩阵乘法，同x1.dot(x2)
print('点乘:{}'.format(np.dot(x1,x2)))
print(x1.dot(x2))

加法:[ 2.    6.25 10.5  14.75 19.  ]
[ 2.    6.25 10.5  14.75 19.  ]
减法:[ 0.   -0.25 -0.5  -0.75 -1.  ]
[ 0.   -0.25 -0.5  -0.75 -1.  ]
乘法:[ 1.    9.75 27.5  54.25 90.  ]
[ 1.    9.75 27.5  54.25 90.  ]
除法:[1.         0.92307692 0.90909091 0.90322581 0.9       ]
[1.         0.92307692 0.90909091 0.90322581 0.9       ]
乘方:[1.00000000e+00 3.55339983e+01 6.98771243e+03 3.54413136e+06
 3.48678440e+09]
[1.00000000e+00 3.55339983e+01 6.98771243e+03 3.54413136e+06
 3.48678440e+09]
模:[0. 3. 5. 7. 9.]
[0. 3. 5. 7. 9.]
点乘:182.5
182.5


## 统计函数

### 最大最小值

In [38]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# 数组的最大值
print('数组的最大值:{}'.format(np.amax(a)))
# 数组的最小值
print('数组的最小值:{}'.format(np.amin(a)))
# axies=0代表纵向，将数组划分为[1,4,7],[2,5,8],[3,6,9]
print('纵向最大值:{}'.format(np.amax(a,0)))
# axies=1代表横向，将数组划分为[1,2,3],[4,5,6],[7,8,9]
print('横向最大值:{}'.format(np.amax(a,1)))

数组的最大值:9
数组的最小值:1
纵向最大值:[7 8 9]
横向最大值:[3 6 9]


### 最大最小值之差

In [37]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# 数组的最大最小值之差
print('数组的最大最小值之差:{}'.format(np.ptp(a)))
# 纵向最大最小值之差
print('纵向最大最小值之差:{}'.format(np.ptp(a,0)))
# 横向最大最小值之差
print('横向最大最小值之差:{}'.format(np.ptp(a,1)))

数组的最大最小值之差:8
纵向最大最小值之差:[6 6 6]
横向最大最小值之差:[2 2 2]


### 百分位数

In [34]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# 在整个数组中排60%的值
print('整个数组中排60%的值:{}'.format(np.percentile(a,60)))
# 在横向排60%的值
print('在横向排60%的值:{}'.format(np.percentile(a,60,axis=1)))
# 在纵向排60%的值
print('在纵向排60%的值:{}'.format(np.percentile(a,60,axis=0)))

整个数组中排60%的值:5.8
在横向排60%的值:[2.2 5.2 8.2]
在纵向排60%的值:[4.6 5.6 6.6]


### 中位数、平均数

In [33]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# 整个数组的中位数
print('整个数组的中位数:{}'.format(np.median(a)))
# 纵向中位数
print('纵向中位数:{}'.format(np.median(a,0)))
# 横向中位数
print('横向中位数:{}'.format(np.median(a,1)))
# 整个数组的平均数
print('整个数组的平均数:{}'.format(np.mean(a)))
# 纵向平均数
print('纵向平均数:{}'.format(np.mean(a,0)))
# 横向平均数
print('向平均数:{}'.format(np.mean(a,1)))

整个数组的中位数:5.0
纵向中位数:[4. 5. 6.]
横向中位数:[2. 5. 8.]
整个数组的平均数:5.0
纵向平均数:[4. 5. 6.]
向平均数:[2. 5. 8.]


### 加权平均值

In [32]:
import numpy as np

a = np.array([1,2,3])
weights = np.array([2,3,5]) # 按2:3:5权重划分
# 默认权重为1
print('默认权重为1:{}'.format(np.average(a)))
# 按权重求平均
print('按权重求平均:{}'.format(np.average(a,weights=weights)))

默认权重为1:2.0
按权重求平均:2.3


### 标准差、方差

In [31]:
import numpy as np

a = np.array([1,2,3])
# 标准差
print('标准差:{}'.format(np.std(a)))
# 方差
print('方差:{}'.format(np.var(a)))

标准差:0.816496580927726
方差:0.6666666666666666


## 排序

In [30]:
import numpy as np

a = np.array([[9,5,3],[2,7,1]])
# 默认axis为-1，以最后一个轴排序
print('以最后一个轴排序：{}'.format(np.sort(a)))
# None表示将数组看作向量整体排序
print('将数组看作向量整体排序：{}'.format(np.sort(a, axis=None)))
# 按纵轴排序
print('按纵轴排序：{}'.format(np.sort(a, axis=0)))
# 按横轴排序
print('按横轴排序：{}'.format(np.sort(a, axis=1)))
# 指定排序方法
print('指定归并排序：{}'.format(np.sort(a,kind='mergesort',axis=None)))

# 指定排序基准order
person_type = np.dtype({
    'names':['name', 'age', 'Chinese', 'Math', 'English'],
    'formats':['S32','i', 'i', 'i', 'f']})  # 数据类型
"""
  |name|age|Chinese|Math|English
0 |    |   |       |    |       
1 |    |...
"""
peoples = np.array([("ZhangSan",78,23,19, 80.5),("LiSi",25,88,91,87),
       ("WangWu",66,16,82,98.5)],
    dtype=person_type)
# 按名字排序
print('按名字排序：{}'.format(np.sort(peoples,order='name')))
# 先按语文成绩，再按数学成绩排序
print('先按语文成绩，再按数学成绩排序:{}'.format(np.sort(peoples,order=['Chinese','Math'])))

以最后一个轴排序：[[3 5 9]
 [1 2 7]]
将数组看作向量整体排序：[1 2 3 5 7 9]
按纵轴排序：[[2 5 1]
 [9 7 3]]
按横轴排序：[[3 5 9]
 [1 2 7]]
指定归并排序：[1 2 3 5 7 9]
按名字排序：[(b'LiSi', 25, 88, 91, 87. ) (b'WangWu', 66, 16, 82, 98.5)
 (b'ZhangSan', 78, 23, 19, 80.5)]
先按语文成绩，再按数学成绩排序:[(b'WangWu', 66, 16, 82, 98.5) (b'ZhangSan', 78, 23, 19, 80.5)
 (b'LiSi', 25, 88, 91, 87. )]


## 用例

问：以下为一个班级学生姓名与对应科目成绩统计表，用Numpy统计这些人语文、数学、英语的平均成绩，最小、最大成绩，方差、标准差。最后将其总成绩排序按名次输出（总成绩为加权平均成绩，权重为3:5:4）

姓名 | 语文 | 数学 | 英语
:---:|:---:|:---:|:---:
张三 | 90 | 89 | 67
李四 | 88 | 82 | 88
王五 | 77 | 99 | 80
小C  | 95 | 77 | 96
小P  | 98 | 82 | 90

In [79]:
import numpy as np

stu_type = np.dtype({
    'names':['name','Chinese','Math','English'],
    'formats':['S32','i','i','i'],
})
data = [
    ('ZhangSan',90,89,67),
    ('LiSi',88,82,88),
    ('WangWu',77,99,80),
    ('littleC',95,77,96),
    ('littleP',98,82,90),
]
wts = [3,5,4]
grades_list = np.array(data,dtype=stu_type)
print(grades_list)
print('语文平均成绩:{}'.format(np.mean(grades_list[:]['Chinese'])))
print('数学平均成绩:{}'.format(np.mean(grades_list[:]['Math'])))
print('英语平均成绩:{}'.format(np.mean(grades_list[:]['English'])))
print('语文最大:{max},最小成绩:{min}'.format(max=np.amax(grades_list[:]['Chinese']),
                                     min=np.amin(grades_list[:]['Chinese'])))
print('语文方差:{var},标准差:{std}'.format(var=np.var(grades_list[:]['Chinese']),std=np.std(grades_list[:]['Chinese'])))
stus = grades_list[0:5][:]
grades = {}
for i in range(5):
    grade = np.average(np.array(list(stus[i])[1:4]),weights=wts)
    grades[data[i][0]] = grade
for k in sorted(grades,key=grades.__getitem__,reverse=True):
    print(k,grades[k])


[(b'ZhangSan', 90, 89, 67) (b'LiSi', 88, 82, 88) (b'WangWu', 77, 99, 80)
 (b'littleC', 95, 77, 96) (b'littleP', 98, 82, 90)]
语文平均成绩:89.6
数学平均成绩:85.8
英语平均成绩:84.2
语文最大:98,最小成绩:77
语文方差:52.239999999999995,标准差:7.227724399837061
littleP 88.66666666666667
littleC 87.83333333333333
WangWu 87.16666666666667
LiSi 85.5
ZhangSan 81.91666666666667
